services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - rosatom_hack
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - rosatom_hack
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local

networks:
  rosatom_hack:
    driver: bridge